name: Upload complete repo to SFTP

on: [push]

jobs:
  Upload-Files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - uses: MercuryTechnologies/aws-ssm-send-command-action@v0.1.0
        with:
          document-name: 'AWS-RunShellScript'
          targets: '[{"Key":"InstanceIds","Values":[${{ secrets.INSTANCE_ID }}]}]'
          parameters: '{"commands":["sudo -u ec2-user sh /usr/src/dp.sh"]}'
          wait-until-command-executed: true
          max-wait-time: 600
      - name: Execute deployment script on EC2 via SSM
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          instance-ids: ${{ secrets.INSTANCE_ID }}
          command: |
            
      
