name: Upload complete repo to SFTP

on: [push]

jobs:
  Upload-Files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-southeast-1
      - name: Execute deployment script on EC2 via SSM
        uses: peterkimzz/aws-ssm-send-command@v1.2.1
        with:
          instance-ids: ${{ secrets.INSTANCE_ID }}
          command: |
            sudo su - ec2-user
            cd /home/ec2-user/repo/
            git pull origin main
            \cp -r Backend/modules/* /home/ec2-user/newcol/modules/
            cd /home/ec2-user/newcol/
            docker-compose restart
      
